services:
  messagebroker:
    image: rabbitmq:management-alpine

  worker.db:
    image: mcr.microsoft.com/mssql/server:2022-latest

  worker.api:
    image: ${DOCKER_REGISTRY-}workerapi
    build:
      context: .
      dockerfile: src/Worker.API/Dockerfile
